eas_behaviour: fix handling dupliated entries
We can end up with duplicated timestamps sometimes, which causes an
exception to be thrown when attemptong to pivot().

Fix this by removing the duplicate entries before the call to pivot()

Traceback (most recent call last):
  File "/mnt/data/src/lisa-next/tools/exekall/exekall/engine.py", line 1964, in genf
    val = self.callable_(*args, **kwargs)
  File "/mnt/data/src/lisa-next/tools/exekall/exekall/engine.py", line 1676, in __call__
    return __UnboundMethod_self__.__wrapped__(*args, **kwargs)
  File "/mnt/data/src/lisa-next/lisa/trace.py", line 1142, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/data/src/lisa-next/lisa/trace.py", line 1142, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/data/src/lisa-next/lisa/tests/base.py", line 594, in wrapper
    res = func(self, *args, **kwargs)
  File "/mnt/data/src/lisa-next/lisa/tests/scheduler/eas_behaviour.py", line 315, in test_task_placement
    est_power = self._get_estimated_power_df(nrg_model)
  File "/mnt/data/src/lisa-next/lisa/tests/scheduler/eas_behaviour.py", line 263, in _get_estimated_power_df
    task_cpu_df = self._get_task_cpu_df()
  File "/mnt/data/src/lisa-next/lisa/tests/scheduler/eas_behaviour.py", line 142, in _get_task_cpu_df
    df = df.pivot(index=df.index, columns='next_comm').fillna(method='ffill')
  File "/mnt/data/src/lisa-next/.lisa-venv-3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 5628, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "/mnt/data/src/lisa-next/.lisa-venv-3.6/lib/python3.6/site-packages/pandas/core/reshape/pivot.py", line 388, in pivot
    return indexed.unstack(columns)
  File "/mnt/data/src/lisa-next/.lisa-venv-3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 5992, in unstack
    return unstack(self, level, fill_value)
  File "/mnt/data/src/lisa-next/.lisa-venv-3.6/lib/python3.6/site-packages/pandas/core/reshape/reshape.py", line 388, in unstack
    return _unstack_frame(obj, level, fill_value=fill_value)
  File "/mnt/data/src/lisa-next/.lisa-venv-3.6/lib/python3.6/site-packages/pandas/core/reshape/reshape.py", line 411, in _unstack_frame
    constructor=obj._constructor)
  File "/mnt/data/src/lisa-next/.lisa-venv-3.6/lib/python3.6/site-packages/pandas/core/reshape/reshape.py", line 128, in __init__
    self._make_selectors()
  File "/mnt/data/src/lisa-next/.lisa-venv-3.6/lib/python3.6/site-packages/pandas/core/reshape/reshape.py", line 166, in _make_selectors
    raise ValueError('Index contains duplicate entries, '
ValueError: Index contains duplicate entries, cannot reshape

Finished UUID=d7a191b828d84ac788e94b6512c34fe0 EnergyModelWakeMigration[board=sgm776]:test_task_placement
                                                                                      ^^^^^^^^^^^^^^^^^^^
EXCEPTION (ValueError): Index contains duplicate entries, cannot reshape

Signed-off-by: Qais Yousef <qais.yousef@arm.com>