install: Fix GTK dependencies
Travis complains about missing GTK dependencies:

  WARNING: autodoc: failed to import module 'trace' from module 'lisa'; the following exception was raised:
  Traceback (most recent call last):
    File "/home/travis/build/ARM-software/lisa/.lisa-venv3/lib/python3.5/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
      __import__(modname)
    File "/home/travis/build/ARM-software/lisa/lisa/trace.py", line 25, in <module>
      import trappy
    File "/home/travis/build/ARM-software/lisa/external/trappy/trappy/__init__.py", line 28, in <module>
      from trappy.plotter.LinePlot import LinePlot
    File "/home/travis/build/ARM-software/lisa/external/trappy/trappy/plotter/__init__.py", line 23, in <module>
      from . import LinePlot
    File "/home/travis/build/ARM-software/lisa/external/trappy/trappy/plotter/LinePlot.py", line 25, in <module>
      from trappy.plotter.StaticPlot import StaticPlot
    File "/home/travis/build/ARM-software/lisa/external/trappy/trappy/plotter/StaticPlot.py", line 23, in <module>
      import matplotlib.pyplot as plt
    File "/home/travis/build/ARM-software/lisa/.lisa-venv3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 2374, in <module>
      switch_backend(rcParams["backend"])
    File "/home/travis/build/ARM-software/lisa/.lisa-venv3/lib/python3.5/site-packages/matplotlib/__init__.py", line 892, in __getitem__
      plt.switch_backend(rcsetup._auto_backend_sentinel)
    File "/home/travis/build/ARM-software/lisa/.lisa-venv3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 196, in switch_backend
      switch_backend(candidate)
    File "/home/travis/build/ARM-software/lisa/.lisa-venv3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
      backend_mod = importlib.import_module(backend_name)
    File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "/home/travis/build/ARM-software/lisa/.lisa-venv3/lib/python3.5/site-packages/matplotlib/backends/backend_gtk3agg.py", line 6, in <module>
      from . import backend_agg, backend_cairo, backend_gtk3
    File "/home/travis/build/ARM-software/lisa/.lisa-venv3/lib/python3.5/site-packages/matplotlib/backends/backend_gtk3.py", line 14, in <module>
      from ._gtk3_compat import GLib, GObject, Gtk, Gdk
    File "/home/travis/build/ARM-software/lisa/.lisa-venv3/lib/python3.5/site-packages/matplotlib/backends/_gtk3_compat.py", line 43, in <module>
      gi.require_version("Gtk", "3.0")
    File "/home/travis/build/ARM-software/lisa/.lisa-venv3/lib/python3.5/site-packages/gi/__init__.py", line 129, in require_version
      raise ValueError('Namespace %s not available' % namespace)
  ValueError: Namespace Gtk not available

Make it shut up by adding a new package to the dependency list in
install_base_ubuntu.sh.

It is not obvious at all this is a good idea, but we don't really have
an alternative solution yet. And we should be able to revert easily if
need be.

Signed-off-by: Quentin Perret <quentin.perret@arm.com>