utils/wa_results_collector: Fix typo for log
When run wa_results_collector class, it report the error for log:
AttributeError: 'WaResultsCollector' object has no attribute 'log'

This is caused by the typo "self.log.warning", so fix typo to
"self._log.warning".

Signed-off-by: Leo Yan <leo.yan@linaro.org>