doc: device_setup: fix generic_linux device_config example
A copy/paste of the documentation example results in a python
backtrace because the dict keys cannot be quoted:

    wlauto.exceptions.ConfigError: Sytax error in config: keyword can't be an expression (config.py, line XYZ)

Fix by removing the quotes from the keys in the example.

Signed-off-by: Kevin Hilman <khilman@linaro.org>