bart: fix duplicated values of switch-in
Sometimes a task would switch in and then out immediately causing bart
to get confused as the 2 events contain the same timestamp.

Add a check to detect these scenarios and deal with it gracefully.

This was observed on fastmodels where the time is simulated. I couldn't
find an evidence that the fastmodel is doing something wrong as the
traces look sane it's just a task was preempted as soon as it started
running and for some reason the recorded timestamp for these events is
exactly the same. It is assumed an artefact of simulated time where the
distance between the 2 events is too fast that the simulated time didn't
get a chance to advance for the few nanoseconds inbetween the 2 events.

Traceback (most recent call last):
  File "/mnt/data/src/lisa-next/tools/exekall/exekall/engine.py", line 1964, in genf
    val = self.callable_(*args, **kwargs)
  File "/mnt/data/src/lisa-next/tools/exekall/exekall/engine.py", line 1676, in __call__
    return __UnboundMethod_self__.__wrapped__(*args, **kwargs)
  File "/mnt/data/src/lisa-next/lisa/trace.py", line 1142, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/data/src/lisa-next/lisa/tests/scheduler/load_tracking.py", line 511, in test_task_util_avg
    return self._test_all_freq(item_test)
  File "/mnt/data/src/lisa-next/lisa/tests/scheduler/load_tracking.py", line 532, in _test_all_freq
    for item in self.invariance_items
  File "/mnt/data/src/lisa-next/lisa/tests/scheduler/load_tracking.py", line 532, in <dictcomp>
    for item in self.invariance_items
  File "/mnt/data/src/lisa-next/lisa/tests/scheduler/load_tracking.py", line 509, in item_test
    allowed_error_pct=allowed_error_pct
  File "/mnt/data/src/lisa-next/lisa/trace.py", line 1142, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/data/src/lisa-next/lisa/tests/scheduler/load_tracking.py", line 375, in test_task_util_avg
    return self._test_signal('util', allowed_error_pct)
  File "/mnt/data/src/lisa-next/lisa/trace.py", line 1142, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/data/src/lisa-next/lisa/tests/scheduler/load_tracking.py", line 343, in _test_signal
    signal_name, allowed_error_pct, self.trace, self.cpu, name, capacity)
  File "/mnt/data/src/lisa-next/lisa/trace.py", line 1142, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/data/src/lisa-next/lisa/trace.py", line 1142, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/data/src/lisa-next/lisa/tests/scheduler/load_tracking.py", line 304, in _test_task_signal
    exp_signal = self.get_expected_util_avg(trace, cpu, task_name, capacity)
  File "/mnt/data/src/lisa-next/lisa/trace.py", line 1142, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/data/src/lisa-next/lisa/tests/scheduler/load_tracking.py", line 293, in get_expected_util_avg
    duty_cycle_pct = self.get_task_duty_cycle_pct(trace, task_name, cpu)
  File "/mnt/data/src/lisa-next/lisa/tests/scheduler/load_tracking.py", line 126, in get_task_duty_cycle_pct
    return SchedAssert(trace.ftrace, top, execname=task_name).getDutyCycle(window)
  File "/mnt/data/src/lisa-next/external/bart/bart/sched/SchedAssert.py", line 550, in getDutyCycle
    return self.getRuntime(window, percent=True)
  File "/mnt/data/src/lisa-next/external/bart/bart/sched/SchedAssert.py", line 388, in getRuntime
    run_time = agg.aggregate(level="all", window=window)[0]
  File "/mnt/data/src/lisa-next/external/trappy/trappy/stats/Aggregator.py", line 144, in aggregate
    level_res = self._aggfunc(self._result[group[0]], **kwargs)
  File "/mnt/data/src/lisa-next/external/bart/bart/sched/functions.py", line 311, in residency_sum
    len(s_out)))
RuntimeError: Unexpected Lengths: s_in=126, s_out=127

Signed-off-by: Qais Yousef <qais.yousef@arm.com>